#pragma config(Motor,  port1,           leftjoystick,  tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rightmotor,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           leftjoystick2, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftmotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightclaw,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftclaw,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightjoystick2, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightjoystick, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

   while(1==1)
    {
    	 motor[leftjoystick] = vexRT[Ch3];
    	 motor[leftjoystick2] = vexRT[Ch3];
    	 motor[rightjoystick] = vexRT[Ch2];
    	 motor[rightjoystick2] = vexRT[Ch2];


      if(vexRT[Btn6U] == 1)
       {

          motor[rightclaw] = 127;
          motor[leftclaw] = 127;
       }
     else if(vexRT[Btn6D] == 1)
       {
          motor[rightclaw] = -127;
          motor[leftclaw] = -127;
       }
     else
       {
         motor[rightclaw] = 0;
         motor[leftclaw] = 0;
       }

     if(vexRT[Btn5U] == 1)
       {
      	motor[rightmotor] = 127;
      	motor[leftmotor] = 127;
       }
     else if(vexRT[Btn5D] == 1)
       {
      	motor[rightmotor] = -127;
      	motor[leftmotor] = -127;
       }
     else
       {
      	motor[rightmotor] = 0;
      	motor[leftmotor] = 0;
       }
    }
 }

