#pragma config(Motor,  port1,           leftjoystick,  tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rightmotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftjoystick2, tmotorNone, openLoop)
#pragma config(Motor,  port4,           leftmotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightclaw,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftclaw,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightjoystick2, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightjoystick, tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  motor[leftjoystick] = 127;
  motor[leftjoystick2] = 127;
  motor[rightjoystick] = 127;
	motor[rightjoystick2]  = 127;

			wait1Msec(2460);

			motor[rightjoystick] = 0;
			motor[rightjoystick2] = 0;
			motor[leftjoystick]  = 0;
			motor[leftjoystick2]= 0;
			motor[armMotor] = 75;
			wait1Msec(1000);



			motor[clawMotor] = 127;
			wait1Msec(2000);
			motor[rightjoystick] = -50;
			motor[leftjoystick] = -50;
			wait1Msec(1000);
			motor[rightjoystick] = 0;
			motor[leftjoystick]  = 0;


}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
 while(1==1)
    {
    	 motor[leftjoystick] = vexRT[Ch3];
    	 motor[leftjoystick2] = vexRT[Ch3];
    	 motor[rightjoystick] = vexRT[Ch2];
    	 motor[rightjoystick2] = vexRT[Ch2];


      if(vexRT[Btn6U] == 1)
       {

          motor[rightclaw] = 127;
          motor[leftclaw] = 127;
       }
     else if(vexRT[Btn6D] == 1)
       {
          motor[rightclaw] = -127;
          motor[leftclaw] = -127;
       }
     else
       {
         motor[rightclaw] = 0;
         motor[leftclaw] = 0;
       }

     if(vexRT[Btn5U] == 1)
       {
      	motor[rightmotor] = 127;
      	motor[leftmotor] = 127;
       }
     else if(vexRT[Btn5D] == 1)
       {
      	motor[rightmotor] = -127;
      	motor[leftmotor] = -127;
       }
     else
       {
      	motor[rightmotor] = 0;
      	motor[leftmotor] = 0;
       }
    }
  }
}
